In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

In [2]:
n = 1000

In [3]:
worker_id = np.arange(1, n + 1)

In [4]:
skills = np.random.choice(
    [
        "Plumbing",
        "Electrical",
        "Carpentry",
        "Cleaning",
        "Painting",
        "Gardening"
    ],
    size=n
)

In [5]:
experience = np.random.randint(1, 21, size=n)

In [6]:
rating = np.round(
    np.random.uniform(3.0, 5.0, size=n),
    1
)

In [7]:
availability = np.random.choice(
    [0, 1],
    size=n,
    p=[0.25, 0.75]
)

In [8]:
workload = np.random.randint(0, 11, size=n)

In [9]:
distance = np.round(
    np.random.uniform(0.5, 20.0, size=n),
    2
)

In [10]:
skill_match = np.random.choice(
    [0, 1],
    size=n,
    p=[0.2, 0.8]
)

In [11]:
df = pd.DataFrame({
    "worker_id": worker_id,
    "skill": skills,
    "skill_match": skill_match,
    "distance": distance,
    "availability": availability,
    "experience": experience,
    "rating": rating,
    "workload": workload
})

In [12]:
df.head()

,worker_id,skill,skill_match,distance,availability,experience,rating,workload
0,1,Cleaning,1,13.94,1,6,4.3,2
1,2,Painting,0,5.42,1,6,3.2,0
2,3,Carpentry,1,6.50,1,16,4.3,6
3,4,Painting,1,12.47,1,4,5.0,3
4,5,Painting,0,18.01,0,11,3.1,0

In [13]:
df["experience_score"] = df["experience"] / 20

In [14]:
df["rating_score"] = df["rating"] / 5

In [15]:
df["distance_score"] = 1 - (df["distance"] / 20)

In [16]:
df["workload_score"] = 1 - (df["workload"] / 10)

In [17]:
df["match_score"] = (
    df["skill_match"] * 0.35 +
    df["distance_score"] * 0.20 +
    df["availability"] * 0.15 +
    df["experience_score"] * 0.10 +
    df["rating_score"] * 0.10 +
    df["workload_score"] * 0.10
)

In [18]:
df["match_score"] = df["match_score"] * 100

In [19]:
df.head(10)

,worker_id,skill,skill_match,distance,availability,experience,rating,workload,experience_score,rating_score,distance_score,workload_score,match_score
0,1,Cleaning,1,13.94,1,6,4.3,2,0.30,0.86,0.3030,0.8,75.66
1,2,Painting,0,5.42,1,6,3.2,0,0.30,0.64,0.7290,1.0,48.98
2,3,Carpentry,1,6.50,1,16,4.3,6,0.80,0.86,0.6750,0.4,84.10
3,4,Painting,1,12.47,1,4,5.0,3,0.20,1.00,0.3765,0.7,76.53
4,5,Painting,0,18.01,0,11,3.1,0,0.55,0.62,0.0995,1.0,23.69
5,6,Electrical,1,16.29,1,9,5.0,7,0.45,1.00,0.1855,0.3,71.21
6,7,Carpentry,1,11.87,0,3,3.8,5,0.15,0.76,0.4065,0.5,57.23
7,8,Carpentry,0,14.74,1,19,4.7,5,0.95,0.94,0.2630,0.5,44.16
8,9,Carpentry,1,7.61,1,8,4.6,1,0.40,0.92,0.6195,0.9,84.59
9,10,Painting,1,13.00,0,5,4.1,0,0.25,0.82,0.3500,1.0,62.70

In [20]:
df.describe()

,worker_id,skill_match,distance,availability,experience,rating,workload,experience_score,rating_score,distance_score,workload_score,match_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,0.788000,10.188540,0.754000,10.386000,3.993100,5.080000,0.519300,0.798620,0.490573,0.492000,66.800660
std,288.819436,0.408929,5.587005,0.430894,5.776016,0.573735,3.131358,0.288801,0.114747,0.279350,0.313136,17.152182
min,1.000000,0.000000,0.500000,0.000000,1.000000,3.000000,0.000000,0.050000,0.600000,0.002000,0.000000,13.600000
25%,250.750000,1.000000,5.350000,1.000000,5.000000,3.500000,2.000000,0.250000,0.700000,0.245000,0.200000,56.652500
50%,500.500000,1.000000,10.000000,1.000000,10.000000,4.000000,5.000000,0.500000,0.800000,0.500000,0.500000,71.720000
75%,750.250000,1.000000,15.100000,1.000000,15.000000,4.500000,8.000000,0.750000,0.900000,0.732500,0.800000,79.682500
max,1000.000000,1.000000,19.960000,1.000000,20.000000,5.000000,10.000000,1.000000,1.000000,0.975000,1.000000,96.070000

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   worker_id         1000 non-null   int64
 1   skill             1000 non-null   str
 2   skill_match       1000 non-null   int64
 3   distance          1000 non-null   float64
 4   availability      1000 non-null   int64
 5   experience        1000 non-null   int32
 6   rating            1000 non-null   float64
 7   workload          1000 non-null   int32
 8   experience_score  1000 non-null   float64
 9   rating_score      1000 non-null   float64
 10  distance_score    1000 non-null   float64
 11  workload_score    1000 non-null   float64
 12  match_score       1000 non-null   float64
dtypes: float64(7), int32(2), int64(3), str(1)
memory usage: 93.9 KB

In [23]:
df.head()
df.shape
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   worker_id         1000 non-null   int64
 1   skill             1000 non-null   str
 2   skill_match       1000 non-null   int64
 3   distance          1000 non-null   float64
 4   availability      1000 non-null   int64
 5   experience        1000 non-null   int32
 6   rating            1000 non-null   float64
 7   workload          1000 non-null   int32
 8   experience_score  1000 non-null   float64
 9   rating_score      1000 non-null   float64
 10  distance_score    1000 non-null   float64
 11  workload_score    1000 non-null   float64
 12  match_score       1000 non-null   float64
dtypes: float64(7), int32(2), int64(3), str(1)
memory usage: 93.9 KB

worker_id           0
skill               0
skill_match         0
distance            0
availability        0
experience          0
rating              0
workload            0
experience_score    0
rating_score        0
distance_score      0
workload_score      0
match_score         0
dtype: int64

In [24]:
np.random.seed(42)

probability = (
    0.35 * df["skill_match"] +
    0.20 * df["distance_score"] +
    0.15 * df["availability"] +
    0.10 * df["experience_score"] +
    0.10 * df["rating_score"] +
    0.10 * df["workload_score"]
)

df["selected"] = np.random.binomial(
    1,
    probability
)

In [25]:
df.head()

,worker_id,skill,skill_match,distance,availability,experience,rating,workload,experience_score,rating_score,distance_score,workload_score,match_score,selected
0,1,Cleaning,1,13.94,1,6,4.3,2,0.30,0.86,0.3030,0.8,75.66,1
1,2,Painting,0,5.42,1,6,3.2,0,0.30,0.64,0.7290,1.0,48.98,1
2,3,Carpentry,1,6.50,1,16,4.3,6,0.80,0.86,0.6750,0.4,84.10,1
3,4,Painting,1,12.47,1,4,5.0,3,0.20,1.00,0.3765,0.7,76.53,1
4,5,Painting,0,18.01,0,11,3.1,0,0.55,0.62,0.0995,1.0,23.69,0

In [26]:
df["selected"].value_counts()

selected
1    669
0    331
Name: count, dtype: int64

In [27]:
df.to_csv("worker_matching_dataset.csv", index=False)